services:
  gateway_service:
    container_name: gateway_service
    build:
      context: ../../
      dockerfile: ./services/gateway/docker-build/app/Dockerfile
    environment:
      APP_CONFIG__RUN__HOST: "0.0.0.0"
      APP_CONFIG__RUN__PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:8080/api/v1/healthcheck/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
 