routes:
  - path: /api/v1/healthcheck
    method: GET
    service: parser-service
    url: http://{PARSER_SERVICE_HOST}:{PARSER_SERVICE_PORT}/api/v1/healthcheck
    rate_limit: 20/minute

  - path: /api/v1/healthcheck
    method: GET
    service: ai-service
    url: http://{AI_SERVICE_HOST}:{AI_SERVICE_PORT}/api/v1/healthcheck
    rate_limit: 20/minute

  - path: /api/v1/healthcheck
    method: GET
    service: templater-service
    url: http://{TEMPLATER_SERVICE_HOST}:{TEMPLATER_SERVICE_PORT}/api/v1/healthcheck
    rate_limit: 20/minute

  - path: /api/v1/healthcheck
    method: GET
    service: modifier-service
    url: http://{PARSER_SERVICE_HOST}:{PARSER_SERVICE_PORT}/api/v1/healthcheck
    rate_limit: 20/minute
