services:
  templater_service:
    container_name: templater_service
    build:
      context: ../../
      dockerfile: ./services/templater/docker-build/app/Dockerfile
    environment:
      APP_CONFIG__RUN__HOST: "0.0.0.0"
      APP_CONFIG__RUN__PORT: 7040
    ports:
      - "7040:7040"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:7040/api/v1/healthcheck/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
