services:
  ai_service:
    container_name: ai_service
    build:
      context: ../../
      dockerfile: ./services/ai/docker-build/app/Dockerfile
    environment:
      APP_CONFIG__RUN__HOST: "0.0.0.0"
      APP_CONFIG__RUN__PORT: 7030
    develop:
      watch:
        - action: sync+restart
          path: ./services/ai/app
          target: /app
        - action: sync+restart
          path: ./libs/common/src/common
          target: /libs/common/src/common
        - action: rebuild
          path: ./services/ai/poetry.lock
    ports:
      - "7030:7030"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:7030/api/v1/healthcheck/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
